In [ ]:
import pandas as pd
import sys
import tomllib
from pathlib import Path

In [2]:
# Navigiert vom Notebook-Ordner eine Ebene nach oben zum Projekt-Root
root_dir = Path.cwd().parent
if str(root_dir) not in sys.path:
    sys.path.append(str(root_dir))

print(root_dir)

/Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken

In [3]:
# Pfad zur config.toml
config_path = Path.cwd().parent / "config.toml"

# config oeffnen
with open(config_path, "rb") as f:
    config = tomllib.load(f)

# config ist jetzt ein normales Python-Dictionary
print(config)

{'semgrep_deeper': {'command': ['semgrep', 'scan', '--config=p/owasp-top-ten', '--config=p/default', '--json']}, 'llm': {'key': 'sk-D0F62rXlHHkGZlinlQPItA', 'model': 'jlu/qwen3-coder-next'}, 'semgrep': {'command': ['semgrep', 'scan', '--config=auto', '--json']}, 'remove_files': {'discard_extensions': ['.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.webp', '.avif', '.mp3', '.mp4', '.webm', '.ogg', '.ogv', '.swf', '.ai', '.woff', '.woff2', '.ttf', '.eot', '.otf', '.scss', '.sass', '.css', '.map', '.pdf', '.epub', '.mobi', '.doc', '.odt', '.pptx', '.xlsx', '.ods', '.tex', '.rst', '.txt', '.puml', '.drawio', '.excalidraw', '.csv', '.zip', '.jar', '.war', '.exe', '.pyc', '.snap', '.mbz', '.imscc', '.ds_store', '.keep', '.gitkeep', '.nojekyll', '.lock', '.prettierrc', '.prettierignore', '.nvmrc', '.editorconfig', '.gitattributes', '.codespellignore', '.babelrc', '.browserslistrc', '.rspec', '.ruby-version', '.rbenv-gemsets', '.csproj', '.sln', '.mf', '.xsd', '.wsdl', '.src', '.tf-disable', '.mod', '.002', '.004', '.003', '.001', '.005', '.007', '.006', '.008', '.021', '.019', '.010', '.017', '.016', '.011', '.018', '.020', '.009', '.022', '.014', '.013', '.012', '.015']}, 'primary_code': {'.js': 'JavaScript', '.mjs': 'JavaScript', '.cjs': 'JavaScript', '.jsx': 'JavaScript (React)', '.ts': 'TypeScript', '.tsx': 'TypeScript (React)', '.vue': 'Vue', '.sql': 'SQL', '.py': 'Python', '.java': 'Java', '.php': 'PHP', '.go': 'Go', '.rb': 'Ruby', '.rake': 'Ruby', '.ru': 'Ruby', '.cs': 'C#', '.sh': 'Shell', '.bash_profile': 'Shell', '.bat': 'Batch', '.cmd': 'Batch', '.ps1': 'PowerShell', '.tf': 'HCL', '.proto': 'ProtocolBuffer'}, 'view_templates': {'.css': 'CSS', '.html': 'HTML', '.htm': 'HTML', '.xhtml': 'HTML', '.xml': 'XML', '.ejs': 'EJS-Template', '.hbs': 'Handlebars', '.handlebars': 'Handlebars', '.jsp': 'JSP', '.tag': 'JSP', '.erb': 'ERB-Template', '.mako': 'Mako-Template', '.j2': 'Jinja2', '.razor': 'Razor-Template'}, 'configurations': {'.json': 'JSON', '.jsonc': 'JSON', '.yaml': 'YAML', '.yml': 'YAML', '.toml': 'TOML', '.ini': 'INI', '.cfg': 'Config', '.conf': 'Config', '.properties': 'Properties', '.env': 'Env', '.env-dist': 'Env', '.http': 'HTTP-Request', '.crt': 'Certificate', '.pem': 'Key/Cert', '.pub': 'PublicKey', '.in': 'Config', '.info': 'Config', '.cnf': 'Config', '.npmrc': 'Config', '.coveragerc': 'Config', '.htaccess': 'Config', '.editorconfig': 'Config', '.prettierrc': 'Config', '.prettierignore': 'Config', '.babelrc': 'Config', '.browserslistrc': 'Config', '.nvmrc': 'Config', '.rspec': 'Config', '.ruby-version': 'Config', '.rbenv-gemsets': 'Config'}}

In [4]:
from src import code_directory_analyzer, data_preprocessing

# 1. Laden aller Repos

Initialisierung des Analyzer

In [5]:
analyzer = code_directory_analyzer.CodeDirectoryAnalyzer(config=config)
analyzer

Ergebnisse in ein pd.DataFrame transformiert

In [6]:
df_projects_before = (
    pd.DataFrame(
        analyzer
        .analyze_directory(
            path_of_data = "../data/processed/"
        )
    )
)

Fehler bei /Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript.epub: [Errno 2] No such file or directory: '/Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript.epub'
Fehler bei /Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript.pdf: [Errno 2] No such file or directory: '/Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript.pdf'
Fehler bei /Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript_small.pdf: [Errno 2] No such file or directory: '/Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript_small.pdf'
Fehler bei /Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript.mobi: [Errno 2] No such file or directory: '/Users/msyl16/Desktop/ai_semgrep_sicherheitsluecken/data/processed/Eloquent JavaScript_no starch press_book_2024/html/Eloquent_JavaScript.mobi'

In [7]:
df_projects_before

,name_source,source_markdown,name_file,id_file,programming_language,file_size_byte,file_size_mb,item_type,lines_of_code,logical_lines_of_code,number_comment_line,character_count_all,character_count_code,character_count_comment
0,Full Stack Web Development The Comprehensive G...,None,.gitignore,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,,1621,0.001546,unknown,106,77,0,215,215,0
1,Full Stack Web Development The Comprehensive G...,None,start.js,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JavaScript,805,0.000768,primary_code,24,24,0,99,97,2
2,Full Stack Web Development The Comprehensive G...,None,package-lock.json,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JSON,14293,0.013631,configuration,374,374,0,1515,1515,0
3,Full Stack Web Development The Comprehensive G...,None,package.json,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JSON,263,0.000251,configuration,14,14,0,28,28,0
4,Full Stack Web Development The Comprehensive G...,None,styles.css,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,CSS,712,0.000679,view,51,43,0,98,98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110530,Node.js Web Development_Packt Publishing_book_...,None,vpc.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,2601,0.002481,primary_code,118,94,0,236,236,0
110531,Node.js Web Development_Packt Publishing_book_...,None,outputs.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,134,0.000128,primary_code,2,2,0,16,16,0
110532,Node.js Web Development_Packt Publishing_book_...,None,ec2.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,784,0.000748,primary_code,36,30,0,78,78,0
110533,Node.js Web Development_Packt Publishing_book_...,None,variables.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,287,0.000274,primary_code,11,11,0,32,32,0
110534,Node.js Web Development_Packt Publishing_book_...,None,main.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,868,0.000828,primary_code,36,31,0,100,100,0

# 2. Join mit manueller Tabelle

In [8]:
path_excel = "../data/Excel/Metadaten_Lehrmaterialien.ods"

In [9]:
df_excel = pd.read_excel(path_excel)
df_excel

,id,id_name,title_name,author,institution,medium,context_type,level,year,license,language,download_url,search_thread,search_location,note
0,1,Learning Web Design _O'Reilly_book_2025,Learning Web Design,Jennifer Niederst Robbins,O'Reilly,book,exercises,beginner,2025.0,MIT License,english,https://learningwebdesign.com,"""Best books"" AND (""Web Development"" OR ""Webent...",Google,https://crocoblock.com/blog/best-web-developme...
1,2,"Learning PHP, MySQL & JavaScript_O'Reilly_book...","Learning PHP, MySQL & JavaScript",Robin Nixon,O'Reilly,book,Step-by-step,beginner,2021.0,O'Really free,english,https://github.com/RobinNixon/lpmj6/tree/master,"""Best books"" AND (""Web Development"" OR ""Webent...",Google,https://mikkegoes.com/web-development-books/
2,3,JavaScript The Definitive Guide_O'Reilly_book_...,JavaScript The Definitive Guide,David Flanagan,O'Reilly,book,Step-by-step,intermediate_advanced,2020.0,O'Really free,english,https://github.com/davidflanagan/jstdg7,"""Best books"" AND (""Web Development"" OR ""Webent...",Google,https://crocoblock.com/blog/best-web-developme...
3,4,Eloquent JavaScript_no starch press_book_2024,Eloquent JavaScript,Marjin Haverbeke,no starch press,book,NaN,beginner,2024.0,MIT License,english,https://github.com/marijnh/Eloquent-JavaScript,"""Best books"" AND (""Web Development"" OR ""Webent...",Google,https://mikkegoes.com/web-development-books/
4,5,Webprogrammierung_DHBW Karlsruhe_university_2019,Webprogrammierung,Dennis Schulmeister-Zimolong,DHBW Karlsruhe,university,lecture,intermediate,2019.0,CC-BY 4.0,german,https://github.com/DennisSchulmeister/dhbwka-w...,"""Vorlesung"" in:readme",GitHub,NaN
5,6,262181 Web Application Development_Heilbronn U...,262181 Web Application Development,Andreas Heil,Heilbronn University for Applied Sciences,university,lecture,intermediate,2020.0,MIT License,german,https://github.com/aheil/hhn-webdev,"""vorlesung"" in:readme ""web application""",GitHub,NaN
6,7,VS1lab_Karlsruhe University_university_2021,VS1lab,Christian Zirpins,Karlsruhe University,university,exercises,intermediate,2021.0,MIT License,german,https://github.com/zirpins/vs1lab,"""Vorlesung"" web* in:readme",GitHub,NaN
7,8,WWI25AMA Programmierung 1_DHBW Mannheim_univer...,WWI25AMA Programmierung 1,NaN,DHBW Mannheim,university,lecture_exercises,beginner,2025.0,MIT License,german,https://github.com/wwi25ama-prog/prog1-material,"""Vorlesung"" web* in:readme",GitHub,NaN
8,9,Webengineering_DHBW Karlsruhe_university_2023,Webengineering,Lukas Panni,DHBW Karlsruhe,university,lecture,beginner,2023.0,CC BY-SA 4.0,german,https://github.com/DHBW-KA-Webengineering/Lect...,"""webengineering"" AND ""lecture"" in:readme",GitHub,NaN
9,10,Ruby on Rails Tutorial_O'Reilly_book_2020,Ruby on Rails Tutorial,Michael Hartl,O'Reilly,book,Step-by-step,beginner,2020.0,MIT License,english,https://github.com/JetBrains/sample_rails_app,"(""Step by Step"" OR ""Tutorial"" OR ""Project-base...",Google Scholar,NaN
10,11,Flask Web Development_O'Reilly_book_2018,Flask Web Development,Miguel Grinberg,O'Reilly,book,Step-by-step,intermediate_advanced,2018.0,MIT License,english,https://github.com/miguelgrinberg/flasky,"(""Step""* OR ""tutorial"" OR ""project""* OR ""hand""...",Google Scholar,NaN
11,12,Ultimate Full-Stack Web Development with MERN_...,Ultimate Full-Stack Web Development with MERN,Nabendu Biswas,Orange Education PVT Ltd,book,NaN,intermediate_advanced,2023.0,MIT License,english,https://github.com/ava-orange-education/Ultima...,(Backend OR Frontend OR Full-Stack OR Fullstac...,JLU-Bib,NaN
12,13,Hands-On Full Stack Development with Spring Bo...,Hands-On Full Stack Development with Spring Bo...,NaN,Packt Publishing,book,NaN,intermediate_advanced,2018.0,MIT License,english,https://github.com/PacktPublishing/Hands-On-Fu...,(Backend OR Frontend OR Full-Stack OR Fullstac...,JLU-Bib,NaN
13,14,Full-Stack Web Development with Jakarta EE and...,Full-Stack Web Development with Jakarta EE and...,Daniel Andres Pelaez Lopez,Packt Publishing,book,NaN,intermediate_advanced,2021.0,MIT License,english,https://github.com/packtpublishing/full-stack-...,(Backend OR Frontend OR Full-Stack OR Fullstac...,JLU-Bib,NaN
14,15,Learn Python programming_Packt Publishing_book...,Learn Python programming,Fabrizio Romano,Packt Publishing,book,NaN,beginner,2018.0,MIT License,english,https://github.com/packtpublishing/learn-pytho...,(Title:Web Development AND Title:Sec*),JLU-Bib,NaN
15,16,The Fullstack Developer Path_Scrimba_Online-co...,The Fullstack Developer Path,NaN,Scrimba,Online-course,Path,beginner,NaN,MIT License,english,https://github.com/scrimba/learn-fullstack-dev...,best web development course,Youtube,NaN
16,17,Microsoft Web Development for Beginner_Microso...,Microsoft Web Development for Beginner,NaN,Microsoft,Online-course,Tutorial,beginner,NaN,MIT License,english,https://github.com/microsoft/web-dev-for-begin...,open source web application course,Google,NaN
17,18,Learn Web Development_mdn_Online-course_2026,Learn Web Development,NaN,mdn,Online-course,Tutorial,beginner,2026.0,CC0 1.0 Universal,english,https://github.com/mdn/content/tree/main/files...,open source web application course,Google,NaN
18,19,Full Stack Java Script_The Odin Project_Online...,Full Stack Java Script,NaN,The Odin Project,Online-course,Path,intermediate,2026.0,CC BY-NC-SA 4.0,english,https://github.com/TheOdinProject/curriculum/t...,open source web application course,Google,NaN
19,20,Web Development with Django Cookbook_Packt Pub...,Web Development with Django Cookbook,Aidas Bendoraitis,Packt Publishing,book,NaN,intermediate_advanced,2016.0,MIT License,english,https://github.com/PacktPublishing/Web-Develop...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN
20,21,Node.js Web Development_Packt Publishing_book_...,Node.js Web Development,David Herron,Packt Publishing,book,NaN,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN
21,22,Django 3 Web Development Cookbook_Packt Publis...,Django 3 Web Development Cookbook,"Aidas Bendoraitis, Jake Kronika",Packt Publishing,book,NaN,intermediate_advanced,2020.0,MIT License,english,https://github.com/PacktPublishing/Django-3-We...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN
22,23,Web Development with Node & Express_O'Reilly_b...,Web Development with Node & Express,Ethan Brown,O'Reilly,book,NaN,intermediate_advanced,2019.0,O'Really free,english,https://github.com/EthanRBrown/web-development...,Web Development,O'Reilly,NaN
23,24,Web API Development with ASP.NET Core 8_Packt ...,Web API Development with ASP.NET Core 8,Xiaodi Yan,Packt Publishing,book,NaN,intermediate_advanced,2024.0,MIT License,english,https://github.com/PacktPublishing/Web-API-Dev...,Web Development,O'Reilly,NaN
24,25,Professional JavaScript for Web Developers_Wil...,Professional JavaScript for Web Developers,Matt Frisbie,Wiley,book,NaN,Intermediate_advanced,2023.0,MIT License,english,https://github.com/msfrisbie/professional-java...,Web Development,O'Reilly,NaN
25,26,Full Stack Web Development The Comprehensive G...,Full Stack Web Development The Comprehensive G...,Phillip Ackermann,Rheinwerk Computing,book,NaN,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN
26,27,CS50's Web Programming with Python and JavaScr...,CS50's Web Programming with Python and JavaScript,"Brian Yu, David J. Malan",Harvard University,university,Online-course,intermediate,2020.0,CC BY-NC-SA 4.0,english,https://cs50.harvard.edu/web/,web programming courses,Google/Youtube,NaN
27,28,Deep Dive Into Modern Web Development_Universi...,Deep Dive Into Modern Web Development,"Matti Luukkainen, Terveystalo, Kalle Ilves, Ja...",University of Helsinki,Online-course,NaN,beginner,2020.0,CC BY-NC-SA 3.0,english,https://github.com/fullstack-hy2020/fullstack-...,web programming courses,Google,NaN

In [10]:
df_ = (
    data_preprocessing
    .left_join(
        df_projects_before,
        df_excel, # manual created table
        ["name_source", "id_name"]
    )
)

# 3. Vergabe einer eindeutigen ID
* Mehrfaches Nutzen vom pandas.index hat zu Problemen geführt, weshalb eigene ID erstellt wird

In [11]:
df_["laufende_nr"] = range(len(df_))

In [12]:
df_["document_id"] = df_["laufende_nr"].astype(str) + "_" + df_["title_name"] + "_" + df_["name_file"]

In [13]:
df_

,name_source,source_markdown,name_file,id_file,programming_language,file_size_byte,file_size_mb,item_type,lines_of_code,logical_lines_of_code,...,level,year,license,language,download_url,search_thread,search_location,note,laufende_nr,document_id
0,Full Stack Web Development The Comprehensive G...,None,.gitignore,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,,1621,0.001546,unknown,106,77,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,0,0_Full Stack Web Development The Comprehensive...
1,Full Stack Web Development The Comprehensive G...,None,start.js,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JavaScript,805,0.000768,primary_code,24,24,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,1,1_Full Stack Web Development The Comprehensive...
2,Full Stack Web Development The Comprehensive G...,None,package-lock.json,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JSON,14293,0.013631,configuration,374,374,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,2,2_Full Stack Web Development The Comprehensive...
3,Full Stack Web Development The Comprehensive G...,None,package.json,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JSON,263,0.000251,configuration,14,14,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,3,3_Full Stack Web Development The Comprehensive...
4,Full Stack Web Development The Comprehensive G...,None,styles.css,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,CSS,712,0.000679,view,51,43,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,4,4_Full Stack Web Development The Comprehensive...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110530,Node.js Web Development_Packt Publishing_book_...,None,vpc.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,2601,0.002481,primary_code,118,94,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110530,110530_Node.js Web Development_vpc.tf
110531,Node.js Web Development_Packt Publishing_book_...,None,outputs.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,134,0.000128,primary_code,2,2,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110531,110531_Node.js Web Development_outputs.tf
110532,Node.js Web Development_Packt Publishing_book_...,None,ec2.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,784,0.000748,primary_code,36,30,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110532,110532_Node.js Web Development_ec2.tf
110533,Node.js Web Development_Packt Publishing_book_...,None,variables.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,287,0.000274,primary_code,11,11,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110533,110533_Node.js Web Development_variables.tf
110534,Node.js Web Development_Packt Publishing_book_...,None,main.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,868,0.000828,primary_code,36,31,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110534,110534_Node.js Web Development_main.tf

Cache result

In [14]:
df_.to_parquet("../data/parquet/df_projects_before.parquet")

# 4. Filtern der Daten

* Jede Datei hat auf Basis seiner Endung eine Klassifizierung erhalten:
    * `primary_code`, `view_templates`, `configurations` und `unknown`
* Da nicht jede Datei bei der Filternung abgefangen werden konnte, wird nochmal manuell untersucht

In [15]:
remove_extensions = config["remove_files"]["discard_extensions"]

In [16]:
# Zeilen behalten, deren Wert NICHT in remove_dtypes enthalten ist
df_projects_after = df_[~df_["programming_language"].isin(remove_extensions)]

Vergleich Daten mit / ohne Datenvorverarbeitung

In [17]:
print(f"Anzahl Vorher: {df_.shape[0]}")
print(f"Anzahl Nachher: {df_projects_after.shape[0]}")
print(f"Prozentuale Differenz: {round(1 - (df_projects_after.shape[0] / df_.shape[0]), 2) * 100}")

Anzahl Vorher: 110535
Anzahl Nachher: 76622
Prozentuale Differenz: 31.0

In [18]:
df_projects_after

,name_source,source_markdown,name_file,id_file,programming_language,file_size_byte,file_size_mb,item_type,lines_of_code,logical_lines_of_code,...,level,year,license,language,download_url,search_thread,search_location,note,laufende_nr,document_id
0,Full Stack Web Development The Comprehensive G...,None,.gitignore,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,,1621,0.001546,unknown,106,77,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,0,0_Full Stack Web Development The Comprehensive...
1,Full Stack Web Development The Comprehensive G...,None,start.js,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JavaScript,805,0.000768,primary_code,24,24,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,1,1_Full Stack Web Development The Comprehensive...
2,Full Stack Web Development The Comprehensive G...,None,package-lock.json,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JSON,14293,0.013631,configuration,374,374,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,2,2_Full Stack Web Development The Comprehensive...
3,Full Stack Web Development The Comprehensive G...,None,package.json,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,JSON,263,0.000251,configuration,14,14,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,3,3_Full Stack Web Development The Comprehensive...
4,Full Stack Web Development The Comprehensive G...,None,styles.css,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,CSS,712,0.000679,view,51,43,...,intermediate,2024.0,NaN,english,https://github.com/cleancoderocker/webhandbuch...,Web Development,O'Reilly,NaN,4,4_Full Stack Web Development The Comprehensive...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110530,Node.js Web Development_Packt Publishing_book_...,None,vpc.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,2601,0.002481,primary_code,118,94,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110530,110530_Node.js Web Development_vpc.tf
110531,Node.js Web Development_Packt Publishing_book_...,None,outputs.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,134,0.000128,primary_code,2,2,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110531,110531_Node.js Web Development_outputs.tf
110532,Node.js Web Development_Packt Publishing_book_...,None,ec2.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,784,0.000748,primary_code,36,30,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110532,110532_Node.js Web Development_ec2.tf
110533,Node.js Web Development_Packt Publishing_book_...,None,variables.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,287,0.000274,primary_code,11,11,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110533,110533_Node.js Web Development_variables.tf
110534,Node.js Web Development_Packt Publishing_book_...,None,main.tf,/Users/msyl16/Desktop/ai_semgrep_sicherheitslu...,HCL,868,0.000828,primary_code,36,31,...,beginner,2016.0,MIT License,english,https://github.com/PacktPublishing/Node.js-Web...,Title:Web Development OR Title:Web Engineering...,JLU-Bib,NaN,110534,110534_Node.js Web Development_main.tf

Nan Data

In [19]:
# (
#     df_files["id_name"]
#     .value_counts()
#     .plot
#     .barh(
#         logx=True
#     )
# )
print(df_projects_after["id_name"].value_counts(dropna=False))

id_name
Learn Web Development_mdn_Online-course_2026                                                    26062
Microsoft Web Development for Beginner_Microsoft_Online-course_                                 21522
Deep Dive Into Modern Web Development_University of Helsinki_Online-course_2020                  8467
The Fullstack Developer Path_Scrimba_Online-course_                                              8313
Professional JavaScript for Web Developers_Wiley_book_2023                                       1811
Web Development with Django Cookbook_Packt Publishing_book_2016                                  1544
Web API Development with ASP.NET Core 8_Packt Publishing_book_2024                               1317
Django 3 Web Development Cookbook_Packt Publishing_book_2020                                     1145
Ultimate Full-Stack Web Development with MERN_Orange Education PVT Ltd_book_2023                 1052
Node.js Web Development_Packt Publishing_book_2016                                                782
Full Stack Java Script_The Odin Project_Online-course_2026                                        741
Webprogrammierung_DHBW Karlsruhe_university_2019                                                  695
Learning PHP, MySQL & JavaScript_O'Reilly_book_2021                                               449
CS50's Web Programming with Python and JavaScript_Harvard University_university_2020              392
Full Stack Web Development The Comprehensive Guide_Rheinwerk Computing_book_2024                  378
Learn Python programming_Packt Publishing_book_2018                                               353
Web Development with Node & Express_O'Reilly_book_2019                                            336
WWI25AMA Programmierung 1_DHBW Mannheim_university_2025                                           198
Ruby on Rails Tutorial_O'Reilly_book_2020                                                         183
Learning Web Design _O'Reilly_book_2025                                                           177
Hands-On Full Stack Development with Spring Boot 2. 0 and React_Packt Publishing_book_2018        136
Eloquent JavaScript_no starch press_book_2024                                                     133
JavaScript The Definitive Guide_O'Reilly_book_2020                                                125
VS1lab_Karlsruhe University_university_2021                                                        83
Webengineering_DHBW Karlsruhe_university_2023                                                      82
Flask Web Development_O'Reilly_book_2018                                                           73
262181 Web Application Development_Heilbronn University for Applied Sciences_university_2020       72
Full-Stack Web Development with Jakarta EE and Vue.js_Packt Publishing_book_2021                    1
Name: count, dtype: int64

In [20]:
df_projects_after[df_projects_after["id_name"].isna()] # Merge und Datenbereinigung hat gut geklappt

Empty DataFrame
Columns: [name_source, source_markdown, name_file, id_file, programming_language, file_size_byte, file_size_mb, item_type, lines_of_code, logical_lines_of_code, number_comment_line, character_count_all, character_count_code, character_count_comment, id, id_name, title_name, author, institution, medium, context_type, level, year, license, language, download_url, search_thread, search_location, note, laufende_nr, document_id]
Index: []

[0 rows x 31 columns]

# 5. Verschlankern der Tabelle durch Entfernung von Metadaten

In [21]:
drop_columns = [
    'name_source',
    'file_size_mb',
    'number_comment_line',
    'character_count_all',
    'character_count_code',
    'character_count_comment',
    'id',
    'context_type',
    'license',
    'language',
    'download_url', 
    'search_thread', 
    'search_location', 
    'note',
    'laufende_nr'
]

In [22]:
df_projects_after = df_projects_after.drop(columns=drop_columns)

Cache result

In [23]:
df_projects_after.to_parquet("../data/parquet/df_filtered.parquet")